from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

AUTO_MARKER = "AUTO-GENERATED BY WORKBOT."
PLACEHOLDER_RE = re.compile(r"\{\{([A-Z0-9_]+)\}\}")


def _list(value: Any) -> list[str]:
    if isinstance(value, (list, tuple)):
        return [str(x) for x in value if str(x).strip()]
    return []


def build_agents_context(config: dict[str, Any]) -> dict[str, str]:
    im = dict(config.get("im") or {})
    intent = dict(im.get("intent") or {})
    agent = dict(config.get("agent") or {})
    gauss = dict(agent.get("gaussdb_context") or {})
    wk = dict(config.get("workspace_knowledge") or {})
    nodes = dict(config.get("nodes") or {})
    source_roots = _list(wk.get("roots"))
    if gauss.get("source_root"):
        source_roots.append(str(gauss["source_root"]))
    manual_paths = _list(config.get("manual_paths"))
    if gauss.get("manual_root"):
        manual_paths.append(str(gauss["manual_root"]))
    wiki_url = str(gauss.get("wiki_entry_url") or config.get("wiki_url") or "").strip()
    default_node = str(config.get("default_node") or "").strip()
    node_lines = []
    for name, raw in nodes.items():
        if not isinstance(raw, dict):
            continue
        enabled = bool(raw.get("enabled", True))
        ssh_alias = str(raw.get("ssh_alias") or name)
        workspace = str(raw.get("workspace") or raw.get("workspace_root") or "")
        suffix = f"; workspace={workspace}" if workspace else ""
        node_lines.append(f"- {name}: ssh={ssh_alias}; enabled={str(enabled).lower()}{suffix}")
    roots = _list(config.get("workspace_roots")) or source_roots
    ctx = {
        "DEFAULT_NODE": default_node or "Not configured",
        "NODE_LIST": "\n".join(node_lines) or "Not configured",
        "WORKSPACE_ROOT": "\n".join(f"- {x}" for x in roots) or "Not configured",
        "SOURCE_ROOTS": "\n".join(f"- {x}" for x in source_roots) or "Not configured",
        "MANUAL_PATHS": "\n".join(f"- {x}" for x in manual_paths) or "Not configured",
        "WIKI_URL": wiki_url or "Not configured",
        "BOT_ALIASES": ", ".join(_list(intent.get("bot_aliases"))) or "Not configured",
        "SELF_ACCOUNTS": ", ".join(_list(im.get("self_accounts"))) or "Not configured",
        "RAG_ENABLED": str(bool((config.get("rag") or {}).get("enabled", False))).lower(),
        "VISION_ENABLED": str(bool((((im.get("rich_message") or {}).get("image") or {}).get("enabled", False)))).lower(),
    }
    return ctx


def _hash_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def context_hash(context: dict[str, str]) -> str:
    return _hash_text(json.dumps(context, ensure_ascii=False, sort_keys=True, separators=(",", ":")))


def render_agents_template(template: str, context: dict[str, str]) -> str:
    def repl(match: re.Match[str]) -> str:
        return context.get(match.group(1), "Not configured")
    return PLACEHOLDER_RE.sub(repl, template)


def _header(template_hash: str, cfg_hash: str) -> str:
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    return (
        "<!--\nAUTO-GENERATED BY WORKBOT.\nSource:\n  - AGENTS.example.md\n  - config/local.json\n\n"
        "DO NOT EDIT DIRECTLY.\n\n"
        f"template_sha256: {template_hash}\nconfig_sha256: {cfg_hash}\ngenerated_at: {ts}\n-->\n\n"
    )


def needs_regeneration(template_path: str | Path, config: dict[str, Any], output_path: str | Path) -> bool:
    t = Path(template_path).read_text(encoding="utf-8")
    ctx = build_agents_context(config)
    out = Path(output_path)
    if not out.exists():
        return True
    head = out.read_text(encoding="utf-8", errors="replace")[:1200]
    return f"template_sha256: {_hash_text(t)}" not in head or f"config_sha256: {context_hash(ctx)}" not in head


def generate_agents_file(template_path: str | Path, config: dict[str, Any], output_path: str | Path, *, backup_manual: bool = True) -> Path:
    template_path, output_path = Path(template_path), Path(output_path)
    template = template_path.read_text(encoding="utf-8")
    ctx = build_agents_context(config)
    if output_path.exists() and backup_manual:
        existing = output_path.read_text(encoding="utf-8", errors="replace")
        if AUTO_MARKER not in existing:
            backup = output_path.with_name(output_path.name + ".bak-v1122")
            if not backup.exists():
                shutil.copy2(output_path, backup)
    body = render_agents_template(template, ctx)
    output_path.write_text(_header(_hash_text(template), context_hash(ctx)) + body.rstrip() + "\n", encoding="utf-8", newline="\n")
    return output_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config/local.json")
    parser.add_argument("--template", default="AGENTS.example.md")
    parser.add_argument("--output", default="AGENTS.md")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    config_path = Path(args.config)
    if not config_path.exists():
        raise SystemExit(f"config not found: {config_path}")
    cfg = json.loads(config_path.read_text(encoding="utf-8-sig"))
    if args.check:
        return 1 if needs_regeneration(args.template, cfg, args.output) else 0
    generate_agents_file(args.template, cfg, args.output)
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
